// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FeatureExtractor.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class EcritureDesScenariosFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "EcritureDesScenarios.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "EcritureDesScenarios", "In order to get all scenarios in files\r\nAs a lazy developer\r\nI want to the scenar" +
                    "ios written in a file", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "EcritureDesScenarios")))
            {
                FeatureExtractor.Specs.Features.EcritureDesScenariosFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Ecriture d\'un scénario")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EcritureDesScenarios")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ecriture")]
        public virtual void EcritureDUnScenario()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ecriture d\'un scénario", new string[] {
                        "ecriture"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "titre",
                        "scénario"});
            table1.AddRow(new string[] {
                        "Changement d’une tablée",
                        "Soit un materiel\nEt ou la configuration definissant la table 7\nLorsque j\'appelle " +
                            "le mot clef changeTable 7\nAlors le script retourne a volonte OK"});
            table1.AddRow(new string[] {
                        "Changement d’une tablée",
                        "Soit un materiel\nEt ou la configuration definissant la table 7\nLorsque j\'appelle " +
                            "le mot clef changeTable 7\nAlors le script retourne a volonte OK24"});
#line 8
 testRunner.Given("l\'exigence transformée ESD_044 contenant les scénario:", ((string)(null)), table1, "Given ");
#line 12
     testRunner.And("le contexte \"Soit un interpreteur de script\\nEt un agenda\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.When("je génére les fichiers scénarios temporaires", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "ligne"});
            table2.AddRow(new string[] {
                        "\"  Contexte:\""});
            table2.AddRow(new string[] {
                        "\"    Soit un interpreteur de script\""});
            table2.AddRow(new string[] {
                        "\"      Et un agenda"});
            table2.AddRow(new string[] {
                        "\"\""});
            table2.AddRow(new string[] {
                        "\"  Scénario: Changement d’une tablée\""});
            table2.AddRow(new string[] {
                        "\"    Soit un materiel\""});
            table2.AddRow(new string[] {
                        "\"      Et ou la configuration definissant la table 7\""});
            table2.AddRow(new string[] {
                        "\"    Lorsque j\'appelle le mot clef changeTable 7\""});
            table2.AddRow(new string[] {
                        "\"    Alors le script retourne a volonte OK\""});
            table2.AddRow(new string[] {
                        "\"\""});
            table2.AddRow(new string[] {
                        "\"  Scénario: Changement d’une tablée\""});
            table2.AddRow(new string[] {
                        "\"    Soit un materiel\""});
            table2.AddRow(new string[] {
                        "\"      Et ou la configuration definissant la table 7\""});
            table2.AddRow(new string[] {
                        "\"    Lorsque j\'appelle le mot clef changeTable 7\""});
            table2.AddRow(new string[] {
                        "\"    Alors le script retourne a volonte OK24\""});
#line 14
 testRunner.Then("j\'ai le fichier contient ESD_044.feature contient les lignes:", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
